using './template.bicep'

param privateDnsZones_azure_api_net_name = null

param privateDnsZones_scm_azure_api_net_name = null

param privateDnsZones_portal_azure_api_net_name = null

param privateDnsZones_privatelink_azurecr_io_name = null

param privateDnsZones_developer_azure_api_net_name = null

param privateDnsZones_privatelink_azconfig_io_name = null

param privateDnsZones_management_azure_api_net_name = null

param privateDnsZones_privatelink_azure_api_net_name = null

param privateDnsZones_privatelink_eastus_azmk8s_io_name = null

param privateDnsZones_privatelink_openai_azure_com_name = null

param privateDnsZones_eastus_privatelink_azurecr_io_name = null

param privateDnsZones_privatelink_azurewebsites_net_name = null

param privateDnsZones_privatelink_grafana_azure_com_name = null

param privateDnsZones_privatelink_monitor_azure_com_name = null

param privateDnsZones_privatelink_search_windows_net_name = null

param privateDnsZones_privatelink_documents_azure_com_name = null

param privateDnsZones_privatelink_vaultcore_azure_net_name = null

param privateDnsZones_privatelink_database_windows_net_name = null

param privateDnsZones_privatelink_dfs_core_windows_net_name = null

param privateDnsZones_privatelink_blob_core_windows_net_name = null

param privateDnsZones_privatelink_file_core_windows_net_name = null

param privateDnsZones_privatelink_queue_core_windows_net_name = null

param privateDnsZones_privatelink_table_core_windows_net_name = null

param privateDnsZones_privatelink_cognitiveservices_azure_com_name = null

param privateDnsZones_privatelink_eastus_prometheus_monitor_azure_com_name = null

param virtualNetworks_EUS_FLLM_DEMO_NET_vnet_externalid = null

param managedClusters_EUS_FLLM_DEMO_APP_BACKEND_aks_externalid = null

param managedClusters_EUS_FLLM_DEMO_APP_FRONTEND_aks_externalid = null