appConfig:
  uri: {{appConfigEndpoint}}
  connectionString: {{appConfigConnectionString}}
azureWorkloadIdentity:
  agentFactoryApiClientId: {{agentFactoryApiMiClientId}}
  agentHubApiClientId: {{agentHubApiMiClientId}}
  chatUiClientId: {{chatUiMiClientId}}
  coreApiClientId: {{coreApiMiClientId}}
  coreJobClientId: {{coreJobMiClientId}}
  dataSourceHubApiClientId: {{dataSourceHubApiMiClientId}}
  gatekeeperApiClientId: {{gatekeeperApiMiClientId}}
  gatekeeperIntegrationApiMiClientId: {{gatekeeperIntegrationApiMiClientId}}
  langChainApiClientId: {{langChainApiMiClientId}}
  managementApiClientId: {{managementApiMiClientId}}
  managementUiClientId: {{managementUiMiClientId}}
  promptHubApiClientId: {{promptHubApiMiClientId}}
  semanticKernelApiClientId: {{semanticKernelApiMiClientId}}
  vectorizationApiClientId: {{vectorizationApiMiClientId}}
  vectorizationJobClientId: {{vectorizationJobMiClientId}}
  tenantId: {{tenantId}}

ingress:
  enabled: true
  protocol: https
  hosts:
  - host: {{serviceHostname}}
    path: {{servicePath}}
    pathType: {{servicePathType}}
  annotations:
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: {{serviceAgwSslCert}}
    appgw.ingress.kubernetes.io/request-timeout: '600'
    kubernetes.iio/ingress.class: azure/application-gateway
