using FoundationaLLM.Common.Interfaces;

namespace FoundationaLLM.Common.Constants
{
    /// <summary>
    /// Name constants used for the key names of the dictionary generated by <see cref="IHttpClientFactoryService"/> implementations.
    /// </summary>
    public static class HttpClientFactoryServiceKeyNames
    {
        /// <summary>
        /// The dictionary key identifying the authentication type of an HTTP client.
        /// </summary>
        public const string AuthenticationType = "AuthenticationType";

        /// <summary>
        /// The dictionary key identifying the endpoint of an HTTP client.
        /// </summary>
        public const string Endpoint = "Endpoint";

        /// <summary>
        /// The dictionary key identifying the API key of an HTTP client.
        /// </summary>
        public const string APIKey = "APIKey";

        /// <summary>
        /// The dictionary key identifying the optional API key prefix.
        /// </summary>
        public const string APIKeyPrefix = "APIKeyPrefix";

        /// <summary>
        /// The dictionary key identifying the name of the header that contains the API key.
        /// </summary>
        public const string APIKeyHeaderName = "APIKeyHeaderName";

        /// <summary>
        /// The dictionary key identifying the API version.
        /// </summary>
        public const string APIVersion = "APIVersion";

        /// <summary>
        /// The dictionary key identifying the timeout in seconds associated with an HTTP client.
        /// </summary>
        public const string TimeoutSeconds = "TimeoutSeconds";

        /// <summary>
        /// The name of the Azure Event Grid topic.
        /// </summary>
        public const string AzureEventGridTopicName = "AzureEventGridTopicName";

        /// <summary>
        /// The name of the Azure Event Grid topic subscription.
        /// </summary>
        public const string AzureEventGridTopicSubscriptionName = "AzureEventGridTopicSubscriptionName";

        /// <summary>
        /// The dictionary key identifying whether diagnostics are enabled for an HTTP client.
        /// </summary>
        public const string EnableDiagnostics = "EnableDiagnostics";

        /// <summary>
        /// The dictionary key identifying whether retry logic is enabled for an HTTP client.
        /// </summary>
        public const string EnableRetry = "EnableRetry";
    }
}
