{{- $name := include "chat-ui.fullname" . -}}
{{- $apihost := include  "chat-ui.apihost" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "chat-ui.name" . }}
    chart: {{ template "chat-ui.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data: 
  AZURE_CLIENT_ID: {{ .Values.azureWorkloadIdentity.chatUiClientId }}
