{{- $name := include "chat-ui.fullname" . -}}

apiVersion: v1
kind: Secret
metadata:
  name: "secret-{{ $name }}"
  labels:
    app: {{ template "chat-ui.name" . }}
    chart: {{ template "chat-ui.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data: 
  NUXT_APP_CONFIG_ENDPOINT: {{ .Values.appConfig.connectionString | b64enc }}
