services:
  chat-api:
    image: ${REGISTRY:-foundationallm}/chat-api:${TAG:-latest}
    build:
      context: ../../
      dockerfile: ./src/ChatAPI/Dockerfile
    ports:
    - "80:80"
    environment:
      DOTNET_URLS: http://+:80
      ASPNETCORE_ENVIRONMENT: Production
      AllowedHosts: '*'
      Logging__Loglevel__Default: 'Debug'
      Logging__Loglevel__Microsoft__AspNetCore: 'Debug'
  langchain-api:
    image: ${REGISTRY:-foundationallm}/langchain-api:${TAG:-latest}
    build:
      context: ../../src/LangChainAPI
      dockerfile: ./Dockerfile
    ports:
    - "8081:80"
    environment:
      SOLLIANCEAICOPILOT__LANGCHAINAPI__KEYVAULTURL: "{{keyVaultUrl}}"
  chat-ui:
    image: ${REGISTRY:-foundationallm}/chat-ui:${TAG:-latest}
    build:
      context: ../../
      dockerfile: ./src/Chat/Dockerfile
    ports:
    - "8080:80"
    environment:
      DOTNET_URLS: http://+:80
      ASPNETCORE_ENVIRONMENT: Production
      AllowedHosts: '*'
      DetailedErrors: 'true'
      Logging__Loglevel__Default: 'Debug'
      Logging__Loglevel__Microsoft__AspNetCore: 'Debug'