namespace FoundationaLLM.Plugins.DataPipeline
{
    public static class PluginParameterNames
    {
        public const string AZUREDATALAKE_DATASOURCE_FOLDERS = "Folders";

        public const string CONTEXTFILE_DATASOURCE_CONTEXTFILEOBJECTID = "ContextFileObjectId";

        public const string SHAREPOINTONLINE_DATASOURCE_DOCUMENTLIBRARIES = "DocumentLibraries";

        public const string TEXTPARTITIONING_DATAPIPELINESTAGE_PARITTIONINGSTRATETGY = "PartitioningStrategy";

        public const string GATEWAYTEXTEMBEDDING_DATAPIPELINESTAGE_KNOWLEDGEUNITOBJECTID = "KnowledgeUnitObjectId";

        public const string AZUREAISEARCHINDEXING_DATAPIPELINESTAGE_KNOWLEDGEUNITOBJECTID = "KnowledgeUnitObjectId";
        public const string AZUREAISEARCHINDEXING_DATAPIPELINESTAGE_VECTORSTOREID = "VectorStoreId";

        public const string KNOWLEDGEEXTRACTION_DATAPIPELINESTAGE_ENTITYEXTRACTIONPROMPTOBJECTID = "PromptObjectId";
        public const string KNOWLEDGEEXTRACTION_DATAPIPELINESTAGE_ENTITYEXTRACTIONCOMPLETIONMODEL = "CompletionModel";
        public const string KNOWLEDGEEXTRACTION_DATAPIPELINESTAGE_ENTITYEXTRACTIONENTITYTYPES = "EntityTypes";
        public const string KNOWLEDGEEXTRACTION_DATAPIPELINESTAGE_ENTITYEXTRACTIONMODELTEMPERATURE = "ModelTemperature";
        public const string KNOWLEDGEEXTRACTION_DATAPIPELINESTAGE_ENTITYEXTRACTIONMAXOUTPUTTOKENCOUNT = "MaxOutputTokenCount";

        public const string KNOWLEDGEGRAPH_DATAPIPELINESTAGE_ENTITYSUMMARIZATIONPROMPTOBJECTID = "PromptObjectId";
        public const string KNOWLEDGEGRAPH_DATAPIPELINESTAGE_ENTITYSUMMARIZATIONCOMPLETIONMODEL = "CompletionModel";
        public const string KNOWLEDGEGRAPH_DATAPIPELINESTAGE_ENTITYSUMMARIZATIONCOMPLETIONMODELTEMPERATURE = "CompletionModelTemperature";
        public const string KNOWLEDGEGRAPH_DATAPIPELINESTAGE_ENTITYSUMMARIZATIONCOMPLETIONMAXOUTPUTTOKENCOUNT = "CompletionMaxOutputTokenCount";
        public const string KNOWLEDGEGRAPH_DATAPIPELINESTAGE_KNOWLEDGEUNITOBJECTID = "KnowledgeUnitObjectId";

        public const string IMAGE_CONTENTTEXTEXTRACTION_AIMODELOBJECTID = "AIModelObjectId";

        public const string IMAGE_METADATATEXTEXTRACTION_AIMODELOBJECTID = "AIModelObjectId";

        public const string TOKEN_CONTENTTEXTPARTITIONING_PARTITIONSIZETOKENS = "PartitionSizeTokens";
        public const string TOKEN_CONTENTTEXTPARTITIONING_PARTITIONOVERLAPTOKENS = "PartitionOverlapTokens";
    }
}
