using System.Text.Json.Serialization;
using FoundationaLLM.Common.Models.OpenAI.Requests;

namespace FoundationaLLM.Common.Models.OpenAI.Responses;

/// <summary>
/// Represents a choice in an OpenAI chat completion response.
/// </summary>
public class OpenAIChatCompletionChoice
{
    /// <summary>
    /// The index of the choice in the list of choices.
    /// </summary>
    [JsonPropertyName("index")]
    public int Index { get; set; }

    /// <summary>
    /// The message generated by the model (for non-streaming responses).
    /// </summary>
    [JsonPropertyName("message")]
    public OpenAIMessage? Message { get; set; }

    /// <summary>
    /// The delta message (for streaming responses).
    /// </summary>
    [JsonPropertyName("delta")]
    public OpenAIMessage? Delta { get; set; }

    /// <summary>
    /// The reason the model stopped generating tokens.
    /// </summary>
    [JsonPropertyName("finish_reason")]
    public string? FinishReason { get; set; }

    /// <summary>
    /// Log probability information for the message (if requested).
    /// </summary>
    [JsonPropertyName("logprobs")]
    public object? Logprobs { get; set; }
}
