# Default values for core-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
serviceAccountName: core-api
image:
  repository: bhm7vnpxv6irqcr.azurecr.io/chatservicewebapi
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

service:
  type: ClusterIP
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

ingress:
  enabled: true
  protocol: https
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: default
    appgw.ingress.kubernetes.io/request-timeout: "600"

env:
  configmap: 
    - name: AZURE_CLIENT_ID
  secret:
    - name: FoundationaLLM__AppConfig__ConnectionString
  values:
    - name: ASPNETCORE_ENVIRONMENT
      value: Production