{{- $name := include "management-api.fullname" . -}}

apiVersion: v1
kind: Secret
metadata:
  name: "secret-{{ $name }}"
  labels:
    app: {{ template "management-api.name" . }}
    chart: {{ template "management-api.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  FoundationaLLM__AppConfig__ConnectionString: {{ .Values.appConfig.connectionString | b64enc }}
