appConfig:
  uri: {{appConfigEndpoint}}
  connectionString: {{appConfigConnectionString}}
azureWorkloadIdentity:
  agentFactoryApiClientId: {{agentFactoryApiMiClientId}}
  agentHubApiClientId: {{agentHubApiMiClientId}}
  chatUiClientId: {{chatUiMiClientId}}
  coreApiClientId: {{coreApiMiClientId}}
  coreJobClientId: {{coreJobMiClientId}}
  dataSourceHubApiClientId: {{dataSourceHubApiMiClientId}}
  gatekeeperApiClientId: {{gatekeeperApiMiClientId}}
  langChainApiClientId: {{langChainApiMiClientId}}
  promptHubApiClientId: {{promptHubApiMiClientId}}
  semanticKernelApiClientId: {{semanticKernelApiMiClientId}}
  tenantId: {{tenantId}}