using './template.bicep'

param containerGroups_EUS_FLLM_DEMO_OPS_tfca_aci_workspaceKey = null

param grafana_efllmdopsgd_name = null

param vaults_EUS_FLLM_DEMO_OPS_kv_name = null

param accounts_eus_fllm_demo_ops_amw_name = null

param components_EUS_FLLM_DEMO_OPS_ai_name = null

param storageAccounts_eusfllmdemoopssa_name = null

param actionGroups_EUS_FLLM_DEMO_OPS_ag_name = null

param registries_EUSFLLMDEMOOPScr_name = null

param privateEndpoints_EFLLMdOPS_grafana_pe_name = null

param privateEndpoints_EUS_FLLM_DEMO_OPS_kv_pe_name = null

param privateEndpoints_EUS_FLLM_DEMO_OPS_dfs_pe_name = null

param privateEndpoints_EUS_FLLM_DEMO_OPS_web_pe_name = null

param privatelinkscopes_EUS_FLLM_DEMO_OPS_ampls_name = null

param privateEndpoints_EUS_FLLM_DEMO_OPS_blob_pe_name = null

param privateEndpoints_EUS_FLLM_DEMO_OPS_file_pe_name = null

param privateEndpoints_EUS_FLLM_DEMO_OPS_queue_pe_name = null

param privateEndpoints_EUS_FLLM_DEMO_OPS_table_pe_name = null

param workspaces_EUS_FLLM_DEMO_OPS_la_name = null

param privateEndpoints_EUS_FLLM_DEMO_OPS_registry_pe_name = null

param dataCollectionRules_MSVMI_EUS_FLLM_DEMO_OPS_la_name = null

param privateEndpoints_EUS_FLLM_DEMO_OPS_appconfig_pe_name = null

param metricAlerts_EUS_FLLM_DEMO_OPS_kv_latency_alert_name = null

param virtualMachineScaleSets_EUS_FLLM_DEMO_OPS_ado_vmss_name = null

param actionGroups_Application_Insights_Smart_Detection_name = null

param metricAlerts_EUS_FLLM_DEMO_OPS_ado_vmss_cpu_alert_name = null

param metricAlerts_EUS_FLLM_DEMO_OPS_tfca_aci_cpu_alert_name = null

param metricAlerts_EUS_FLLM_DEMO_OPS_tfca_aci_ram_alert_name = null

param privateEndpoints_EUS_FLLM_DEMO_OPS_azuremonitor_pe_name = null

param metricAlerts_EUS_FLLM_DEMO_OPS_ado_vmss_disk_alert_name = null

param metricAlerts_EUS_FLLM_DEMO_OPS_kv_saturation_alert_name = null

param userAssignedIdentities_EUS_FLLM_DEMO_OPS_mi_name = null

param containerGroups_EUS_FLLM_DEMO_OPS_tfca_aci_name = null

param metricAlerts_EUS_FLLM_DEMO_OPS_kv_availability_alert_name = null

param metricAlerts_EUS_FLLM_DEMO_OPS_sa_availability_alert_name = null

param solutions_Security_eus_fllm_demo_ops_la__name = null

param scheduledqueryrules_EUS_FLLM_DEMO_OPS_la_issues_alert_name = null

param metricAlerts_EUS_FLLM_DEMO_OPS_appconfig_latency_alert_name = null

param privateEndpoints_EUS_FLLM_DEMO_OPS_prometheusMetrics_pe_name = null

param configurationStores_eus_fllm_demo_ops_appconfig_name = null

param scheduledqueryrules_EUS_FLLM_DEMO_OPS_la_rate_limit_alert_name = null

param metricAlerts_EUS_FLLM_DEMO_OPS_appconfig_storageUsage_alert_name = null

param scheduledqueryrules_EUS_FLLM_DEMO_OPS_la_ingestion_cap_alert_name = null

param solutions_ContainerInsights_EUS_FLLM_DEMO_OPS_la__name = null

param solutions_SecurityCenterFree_EUS_FLLM_DEMO_OPS_la__name = null

param systemTopics_eusfllmdemoopssa_d63dac3c_9957_4c24_9baf_ffb984d8ffc4_name = null

param solutions_SQLVulnerabilityAssessment_eus_fllm_demo_ops_la__name = null

param solutions_SQLAdvancedThreatProtection_eus_fllm_demo_ops_la__name = null

param smartdetectoralertrules_failure_anomalies___eus_fllm_demo_ops_ai_name = null

param virtualNetworks_EUS_FLLM_DEMO_NET_vnet_externalid = null

param privateDnsZones_privatelink_grafana_azure_com_externalid = null

param privateDnsZones_privatelink_azconfig_io_externalid = null

param privateDnsZones_privatelink_blob_core_windows_net_externalid = null

param privateDnsZones_privatelink_monitor_azure_com_externalid = null

param privateDnsZones_privatelink_dfs_core_windows_net_externalid = null

param privateDnsZones_privatelink_file_core_windows_net_externalid = null

param privateDnsZones_privatelink_vaultcore_azure_net_externalid = null

param privateDnsZones_privatelink_eastus_prometheus_monitor_azure_com_externalid = null

param privateDnsZones_privatelink_queue_core_windows_net_externalid = null

param privateDnsZones_privatelink_azurecr_io_externalid = null

param privateDnsZones_eastus_privatelink_azurecr_io_externalid = null

param privateDnsZones_privatelink_table_core_windows_net_externalid = null

param privateDnsZones_privatelink_azurewebsites_net_externalid = null