{{- $name := include "prompt-hub-api.fullname" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "prompt-hub-api.name" . }}
    chart: {{ template "prompt-hub-api.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data: 
  AZURE_CLIENT_ID: {{ .Values.azureWorkloadIdentity.promptHubApiClientId }}
  foundationallm-app-configuration-uri: {{ .Values.appConfig.uri }}
