apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: foundationallm-certificates
spec:
  provider: azure
  secretObjects:
    - secretName: coreapi-tls
      type: kubernetes.io/tls
      data:
        - objectName: coreapi
          key: tls.key
        - objectName: coreapi
          key: tls.crt
    - secretName: managementapi-tls
      type: kubernetes.io/tls
      data:
        - objectName: managementapi
          key: tls.key
        - objectName: managementapi
          key: tls.crt
    - secretName: vectorizationapi-tls
      type: kubernetes.io/tls
      data:
        - objectName: vectorizationapi
          key: tls.key
        - objectName: vectorizationapi
          key: tls.crt
  parameters:
    keyvaultName: "{{keyVaultName}}"
    tenantId: "{{tenantId}}"
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "{{aksBackendCsiIdentityClientId}}"
    objects:  |
      array:
        - |
          objectName: coreapi
          objectType: secret
        - |
          objectName: managementapi
          objectType: secret
        - |
          objectName: vectorizationapi
          objectType: secret