{{- $name := include "vectorization-job.fullname" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "vectorization-job.name" . }}
    chart: {{ template "vectorization-job.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data: 
  AZURE_CLIENT_ID: {{ .Values.azureWorkloadIdentity.vectorizationJobClientId }}
