kind: Service
apiVersion: v1
metadata:
  name: {{serviceName}}
spec:
  type: ExternalName
  externalName: {{serviceName}}.{{serviceNamespaceName}}.svc.cluster.local
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{serviceName}}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{serviceHostname}}
      secretName: {{serviceSecretName}}-tls
  rules:
    - host: {{serviceHostname}}
      http:
        paths:
          - path: {{servicePath}}
            pathType: {{servicePathType}}
            backend:
              service:
                name: {{serviceName}}
                port:
                  number: 80
