{{- $name := include "management-ui.fullname" . -}}
{{- $apihost := include  "management-ui.apihost" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "management-ui.name" . }}
    chart: {{ template "management-ui.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data: 
  AZURE_CLIENT_ID: {{ .Values.azureWorkloadIdentity.managementUiClientId }}
  NUXT_APP_BASE_URL: {{ .Values.baseUrl }}
