# Default values for core-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3
serviceAccountName: core-api
image:
  repository: ghcr.io/solliancenet/foundationallm/core-api
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    ephemeral-storage: "100G"
  limits:
    ephemeral-storage: "100G"

nodeSelector: {}

tolerations: []

affinity: {}

ingress:
  enabled: false

env:
  configmap:
    - name: AZURE_CLIENT_ID
  secret:
    - name: FoundationaLLM_AppConfig_ConnectionString
  values:
    - name: ASPNETCORE_ENVIRONMENT
      value: Production