name: Helm Chart Build and Push

on:
  workflow_call:
    inputs:
      registry:
        type: string
        default: ghcr.io
      chart:
        type: string
        required: true
      tag:
        type: string
        required: true
      username:
        type: string
        required: true
      target:
        type: string
        required: true
  
jobs:
  helm_build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get Container Registry Password
      uses: actions/github-script@v7
      id: set-registry-password
      with:
        result-encoding: string
        script: |
          var passwords = new Map()
          passwords['e2e'] = process.env.E2E_ACR_PASSWORD
          passwords['sandbox'] = process.env.SBX_ACR_PASSWORD
          return passwords['${{ inputs.target }}']
      env:
        E2E_ACR_PASSWORD: ${{ secrets.FLLM_E2E_ACR_PASSWORD }}
        SBX_ACR_PASSWORD: ${{ secrets.FLLM_SBX_ACR_PASSWORD }}
    
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ steps.set-registry-password.outputs.result }}

    - name: Helm Chart Update, Package, and Push
      run: |
        cd ./deploy/common/helm/${{ inputs.chart }}
        sed -i "s/version\: 0\.0\.0/version\: ${{ inputs.tag }}/" Chart.yaml
        sed -i "s/tag\: latest/tag\: ${{ inputs.tag }}/" values.yaml
        helm package . --app-version ${{ inputs.tag }}
        helm push ${{ inputs.chart }}-${{ inputs.tag }}.tgz oci://${{ inputs.registry }}/helm
