name: Chat UI Release

on:
  workflow_dispatch:
    inputs: {}

jobs:
  release_docker_image:
    name: Release Docker Image
    uses: ./.github/workflows/release-docker-image.yml
    with:
      image: chat-ui
      context: ./src/ui/UserPortal
      dockerfile: ./src/ui/UserPortal/Dockerfile
