name: Gatekeeper Integration API Release

on:
  workflow_dispatch:
    inputs: {}

jobs:
  release_docker_image:
    name: Release Docker Image
    uses: ./.github/workflows/release-docker-image.yml
    with:
      image: gatekeeper-integration-api
      context: ./src/python
      dockerfile: ./src/python/GatekeeperIntegrationAPI/Dockerfile
