name: Management UI Release

on:
  workflow_dispatch:
    inputs: {}

jobs:
  release_docker_image:
    name: Release Docker Image
    uses: ./.github/workflows/release-docker-image.yml
    with:
      image: management-ui
      context: ./src/ui/ManagementPortal
      dockerfile: ./src/ui/ManagementPortal/Dockerfile
