name: Vectorization Worker Job Release

on:
  workflow_dispatch:
    inputs: {}

jobs:
  release_docker_image:
    name: Release Docker Image
    uses: ./.github/workflows/release-docker-image.yml
    with:
      image: vectorization-job
      context: ./src
      dockerfile: ./src/dotnet/VectorizationWorker/Dockerfile
